[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
    exact = true
    stripComponents = 1
[".vim/pack/plugins/start/vim-go"]
    type = "archive"
    url = "https://github.com/fatih/vim-go/archive/v1.25.tar.gz"
    exact = true
    stripComponents = 1
[".vim/pack/default/start/gruvbox"]
    type = "archive"
    url = "https://github.com/morhetz/gruvbox/archive/master.tar.gz"
    exact = true
    stripComponents = 1
[".vim/pack/plugins/start/completor.vim"]
    type = "archive"
    url = "https://github.com/maralla/completor.vim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
[".vim/pack/plugins/start/gotests-vim"]
    type = "archive"
    url = "https://github.com/buoto/gotests-vim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
[".vim/pack/vendor/start/nerdtree"]
    type = "archive"
    url = "https://github.com/preservim/nerdtree/archive/master.tar.gz"
    exact = true
    stripComponents = 1
